import {screenToWorld,tiltControl} from './controls.js';
import {COURSE,TUNE,newGame,step,clamp} from './physics.js';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');let state=newGame(),started=false,paused=false,tilt=false,tiltSeen=false,tiltInput={x:0,z:0},tiltCenter=null,lastOrientation=null,force=3,last=performance.now(),camera={x:0,z:7},keys=new Set(),presses=new Map(),notice='';
const say=t=>{notice=t;$('message').textContent=t};
const scale=8.4;
function project(x,z,h=0){const X=x-camera.x,Z=z-camera.z;return {x:120+(X-Z)*scale*.70,y:147+(X+Z)*scale*.38-h*scale*.9}}
function polygon(points,fill,stroke='#061520'){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(const p of points.slice(1))ctx.lineTo(p.x,p.y);ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}
function tile(t){const x=t.x,z=t.z,w=t.w/2,l=t.l/2,h=(X,Z)=>t.h+t.dx*(X-x)+t.dz*(Z-z);let corners=[[x-w,z-l],[x+w,z-l],[x+w,z+l],[x-w,z+l]],top=corners.map(([X,Z])=>project(X,Z,h(X,Z)));const bottom=corners.map(([X,Z])=>project(X,Z,h(X,Z)-.65));polygon([top[2],top[3],bottom[3],bottom[2]],'#163543');polygon([top[1],top[2],bottom[2],bottom[1]],'#214858');polygon(top,({start:'#426c68',ramp:'#a17b57',crest:'#557e84',bank:'#498a88',bridge:'#d49a62',turn:'#517c81',goal:'#5b938a'})[t.kind]);ctx.strokeStyle='#def8db99';ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(top[0].x,top[0].y);ctx.lineTo(top[1].x,top[1].y);ctx.stroke()}
function orb(x,z,y,r,color,roll=0){const p=project(x,z,y);const g=ctx.createRadialGradient(p.x-r*.35,p.y-r*.5,1,p.x,p.y,r);g.addColorStop(0,'#fff9db');g.addColorStop(.36,color);g.addColorStop(1,'#29455b');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#173648';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y,r*.73,r*.31,roll,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#fff9ce';ctx.beginPath();ctx.arc(p.x-r*.27,p.y-r*.33,1.5,0,7);ctx.fill()}
function draw(){let sky=ctx.createLinearGradient(0,0,0,282);sky.addColorStop(0,'#203d4c');sky.addColorStop(1,'#08131d');ctx.fillStyle=sky;ctx.fillRect(0,0,240,282);ctx.fillStyle='#8dbdb322';for(let i=0;i<12;i++){const x=(i*83)%240,y=(i*97)%282;ctx.fillRect(x,y,2,2)}
  for(const t of COURSE.tiles)tile(t);
  const cp=COURSE.checkpoints[0],p=project(cp.x,cp.z,1.25);ctx.strokeStyle=state.checkpoint?'#fff4a4':'#9ce7e7';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(p.x,p.y,10,5,-.5,0,7);ctx.stroke();const g=project(COURSE.goal.x,COURSE.goal.z,.6);ctx.strokeStyle='#a1ffe0';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(g.x,g.y,13,7,-.5,0,7);ctx.stroke();for(const post of COURSE.posts)orb(post.x,post.z,(COURSE.tiles.find(t=>Math.abs(post.x-t.x)<=t.w/2&&Math.abs(post.z-t.z)<=t.l/2)?.h||0)+.55,post.r*scale*.8,'#df7770');const shadow=project(state.x,state.z,state.y-TUNE.radius);ctx.fillStyle='#00121daa';ctx.beginPath();ctx.ellipse(shadow.x+3,shadow.y+5,6,2.8,-.45,0,7);ctx.fill();orb(state.x,state.z,state.y,5.5,'#f8b35b',state.roll);}
function sync(){ $('time').textContent=state.remaining.toFixed(1);$('time').style.color=state.remaining<15?'#ff7c77':'#ffe093';$('speed').textContent=`FORCE ${force} ↕`;if(state.status==='finished')say(`FINISH · ${state.remaining.toFixed(1)}s LEFT · ${state.falls} FALLS`);else if(state.status==='timeout')say('TIME UP · RESTART IN MENU');else if(state.fallTime>0)say('FALL · QUICK RESPAWN −4s');else if(state.checkpoint&&notice==='')say('CHECKPOINT');}
function start(){state=newGame();tiltCenter=null;tiltInput={x:0,z:0};camera={x:0,z:7};started=true;paused=false;$('overlay').hidden=true;$('help').hidden=true;say('ROLL TO THE GLOWING GOAL');sync()}
$('start').onclick=start;$('restart').onclick=start;$('menu').onclick=()=>{paused=true;$('help').hidden=false};$('resume').onclick=()=>{paused=false;$('help').hidden=true};
const adjust=d=>{force=clamp(force+d,1,5);sync();say(`FORCE ${force} · ${force<3?'PRECISION':'MOMENTUM'}`)};
addEventListener('wheel',e=>{if(!started)return;e.preventDefault();adjust(e.deltaY>0?-1:1)},{passive:false});let touchY=null;$('speed').addEventListener('pointerdown',e=>{touchY=e.clientY;$('speed').setPointerCapture(e.pointerId)});$('speed').addEventListener('pointerup',e=>{if(touchY!==null)adjust(touchY-e.clientY>8?1:touchY-e.clientY< -8?-1:1);touchY=null});
$('recenter').onclick=()=>{tiltCenter=lastOrientation?{...lastOrientation}:null;tiltInput={x:0,z:0};say(tiltCenter?'TILT RECENTERED':'WAITING FOR TILT SAMPLE')};
$('tilt').onclick=async()=>{try{if(typeof DeviceOrientationEvent==='undefined')throw Error();if(typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!=='granted')throw Error();tilt=true;tiltSeen=false;tiltCenter=null;tiltInput={x:0,z:0};say('HOLD LEVEL · AUTO CENTERING');setTimeout(()=>{if(tilt&&!tiltSeen){tilt=false;say('NO TILT EVENTS · USE TOUCH ARROWS')}},2200)}catch{tilt=false;say('TILT UNAVAILABLE · USE TOUCH ARROWS')}};
addEventListener('deviceorientation',e=>{if(!tilt||!Number.isFinite(e.gamma)||!Number.isFinite(e.beta))return;tiltSeen=true;lastOrientation={gamma:e.gamma,beta:e.beta};if(!tiltCenter){tiltCenter={...lastOrientation};say('TILT CENTERED · RECENTER ANYTIME')}tiltInput=tiltControl(e.gamma,e.beta,tiltCenter)});
for(const b of document.querySelectorAll('[data-dir]')){const dir=b.dataset.dir;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);presses.set(e.pointerId,dir)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,e=>presses.delete(e.pointerId))}
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase())});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function frame(now){const dt=Math.min((now-last)/1000,1/30);last=now;if(started&&!paused){let horizontal=0,vertical=0;const dirs=[...presses.values(),...keys];let brake=dirs.some(d=>d===' '||d==='b')||brakePressed;for(const d of dirs){if(d==='left'||d==='arrowleft'||d==='a')horizontal--;if(d==='right'||d==='arrowright'||d==='d')horizontal++;if(d==='up'||d==='arrowup'||d==='w')vertical--;if(d==='down'||d==='arrowdown'||d==='s')vertical++}// screen-space axes use the same inverse basis as the visible pad
    let {x,z}=screenToWorld(horizontal,vertical);
    if(tilt&&tiltSeen){x+=tiltInput.x;z+=tiltInput.z}state=step(state,{x:clamp(x,-1,1)*force/3,z:clamp(z,-1,1)*force/3,brake},dt);camera.x+=(state.x-camera.x)*Math.min(1,dt*3);camera.z+=(state.z+7-camera.z)*Math.min(1,dt*3);sync();draw()}requestAnimationFrame(frame)}
let brakePressed=false;const brakeButton=$('brake');brakeButton.addEventListener('pointerdown',e=>{e.preventDefault();brakeButton.setPointerCapture(e.pointerId);brakePressed=true});for(const ev of ['pointerup','pointercancel','lostpointercapture'])brakeButton.addEventListener(ev,()=>brakePressed=false);requestAnimationFrame(frame);

window.__lab=()=>({state:{...state},tilt,tiltSeen,tiltCenter,tiltInput:{...tiltInput},force,started});
