import {tiltControl,gesture,isTap,GESTURE} from './controls.js';
import {TUNE,newGame,step,clamp,opponentPosition,surfaceAt} from './physics.js';
import {createCourse,CATALOG,DIFFICULTIES} from './courses.js';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');let selected=1,difficulty='standard',COURSE=createCourse(selected,difficulty),state=newGame(COURSE),started=false,paused=false,tiltSeen=false,tiltInput={x:0,z:0},tiltCenter=null,force=3,last=performance.now(),camera={x:0,z:7},keys=new Set(),notice='',brakePressed=false,jumpQueued=false,orientationTimer=null,motionStatus='idle',lastTap=null,gestureStart=null,muted=true,audioContext=null;
const say=t=>{notice=t;$('message').textContent=t};
const scale=8.4;
function project(x,z,h=0){const X=x-camera.x,Z=z-camera.z;return {x:120+(X-Z)*scale*.70,y:147+(X+Z)*scale*.38-h*scale*.9}}
function polygon(points,fill,stroke='#061520'){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(const p of points.slice(1))ctx.lineTo(p.x,p.y);ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}
function tile(t){const x=t.x,z=t.z,w=t.w/2,l=t.l/2,h=(X,Z)=>t.h+t.dx*(X-x)+t.dz*(Z-z);let corners=[[x-w,z-l],[x+w,z-l],[x+w,z+l],[x-w,z+l]],top=corners.map(([X,Z])=>project(X,Z,h(X,Z)));const bottom=corners.map(([X,Z])=>project(X,Z,h(X,Z)-.65));polygon([top[2],top[3],bottom[3],bottom[2]],'#163543');polygon([top[1],top[2],bottom[2],bottom[1]],'#214858');polygon(top,({start:'#426c68',ramp:'#a17b57',crest:'#557e84',bank:'#498a88',bridge:'#d49a62',turn:'#517c81',goal:'#5b938a'})[t.kind]);ctx.strokeStyle='#def8db99';ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(top[0].x,top[0].y);ctx.lineTo(top[1].x,top[1].y);ctx.stroke()}
function orb(x,z,y,r,color,roll=0){const p=project(x,z,y);const g=ctx.createRadialGradient(p.x-r*.35,p.y-r*.5,1,p.x,p.y,r);g.addColorStop(0,'#fff9db');g.addColorStop(.36,color);g.addColorStop(1,'#29455b');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#173648';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y,r*.73,r*.31,roll,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#fff9ce';ctx.beginPath();ctx.arc(p.x-r*.27,p.y-r*.33,1.5,0,7);ctx.fill()}
function draw(){let sky=ctx.createLinearGradient(0,0,0,282);sky.addColorStop(0,'#203d4c');sky.addColorStop(1,'#08131d');ctx.fillStyle=sky;ctx.fillRect(0,0,240,282);ctx.fillStyle='#8dbdb322';for(let i=0;i<12;i++){const x=(i*83)%240,y=(i*97)%282;ctx.fillRect(x,y,2,2)}
  for(const t of COURSE.tiles)tile(t);
  for(const [i,cp] of COURSE.checkpoints.entries()){const p=project(cp.x,cp.z,1.25);ctx.strokeStyle=state.checkpoint>i?'#fff4a4':'#9ce7e7';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(p.x,p.y,10,5,-.5,0,7);ctx.stroke()}const g=project(COURSE.goal.x,COURSE.goal.z,.6);ctx.strokeStyle='#a1ffe0';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(g.x,g.y,13,7,-.5,0,7);ctx.stroke();for(const post of COURSE.hazards){const h=surfaceAt(post.x,post.z,COURSE)?.h||0;orb(post.x,post.z,h+.55,post.r*scale*.8,post.kind==='bomb'?'#ff3f54':'#df7770');if(post.kind==='bomb'){const p=project(post.x,post.z,h+1);ctx.fillStyle='#ffdc82';ctx.fillRect(p.x-2,p.y-8,4,4)}}for(const [i,f] of COURSE.features.entries()){if(state.collected.includes(i))continue;const p=project(f.x,f.z,.9);ctx.fillStyle=f.effect==='time'?'#f9dc7a':f.effect==='shield'?'#8cebd1':'#9daaff';ctx.beginPath();ctx.moveTo(p.x,p.y-7);ctx.lineTo(p.x+6,p.y);ctx.lineTo(p.x,p.y+7);ctx.lineTo(p.x-6,p.y);ctx.fill()}for(const o of COURSE.opponents){const p=opponentPosition(o,state.elapsed);orb(p.x,p.z,(surfaceAt(p.x,p.z,COURSE)?.h||0)+.55,5,'#b46fe3')}const shadow=project(state.x,state.z,state.y-TUNE.radius);ctx.fillStyle='#00121daa';ctx.beginPath();ctx.ellipse(shadow.x+3,shadow.y+5,6,2.8,-.45,0,7);ctx.fill();orb(state.x,state.z,state.y,5.5,'#f8b35b',state.roll);}
function beep(frequency=520){if(muted||!audioContext)return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=frequency;g.gain.setValueAtTime(.08,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.12);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.12)}
function sync(){ $('time').textContent=state.remaining.toFixed(0)+' · '+Math.max(0,state.lives)+'♥';$('label').textContent=`${String(selected).padStart(2,'0')}/25 ${COURSE.name.toUpperCase()}`;$('time').style.color=state.remaining<15?'#ff7c77':'#ffe093';$('speed').textContent=`FORCE ${force} ↕`;
  if(state.status==='finished'||state.status==='timeout'||state.status==='out'){if($('result').hidden)beep(state.status==='finished'?760:210);$('result').hidden=false;$('next').hidden=state.status!=='finished'||selected===25;$('result-title').textContent=state.status==='finished'?'COURSE COMPLETE':state.status==='out'?'OUT OF LIVES':'TIME UP';$('result-detail').textContent=state.status==='finished'?`${COURSE.name} · ${state.remaining.toFixed(0)}s left · ${state.lives} lives · ${state.falls} falls.`:`${COURSE.name} · ${state.falls} falls · Retry this course.`}
  else if(state.fallTime>0)say(`FALL · ${Math.max(0,state.lives)} LIVES · RESPAWN −4s`);else if(state.checkpoint&&notice==='')say('CHECKPOINT');}
async function prepareTilt(){tiltSeen=false;tiltCenter=null;tiltInput={x:0,z:0};motionStatus='waiting';say('HOLD YOUR PLAYING POSTURE · CALIBRATING TILT');clearTimeout(orientationTimer);
  try{if(typeof DeviceOrientationEvent==='undefined')throw Error('unsupported');if(typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!=='granted')throw Error('permission denied');
    orientationTimer=setTimeout(()=>{if(!tiltSeen){motionStatus='unavailable';say('NO TILT DATA · CHECK MOTION ACCESS, THEN REPLAY')}},2200);
  }catch(e){motionStatus='unavailable';say(`TILT UNAVAILABLE (${e.message}) · CHECK MOTION ACCESS, THEN REPLAY`)}
}
function start(){COURSE=createCourse(selected,difficulty);state=newGame(COURSE);camera={x:0,z:7};started=true;paused=false;jumpQueued=false;lastTap=null;$('overlay').hidden=true;$('help').hidden=true;$('result').hidden=true;prepareTilt();sync()}
$('start').onclick=start;$('restart').onclick=start;$('replay').onclick=start;$('next').onclick=()=>{selected=Math.min(25,selected+1);$('course').value=String(selected);start()};$('course').onchange=e=>{selected=Number(e.target.value);COURSE=createCourse(selected,difficulty);state=newGame(COURSE);sync()};$('difficulty').onchange=e=>{difficulty=e.target.value;COURSE=createCourse(selected,difficulty);state=newGame(COURSE);sync()};
function openDrawer(){if(!started||!$('result').hidden)return;paused=true;lastTap=null;$('help').hidden=false}
function closeDrawer(){paused=false;$('help').hidden=true;lastTap=null}
$('resume').onclick=closeDrawer;
const adjust=d=>{force=clamp(force+d,1,5);sync();say(`FORCE ${force} · ${force<3?'PRECISION':'MOMENTUM'}`)};
addEventListener('wheel',e=>{if(!started||paused||!$('result').hidden)return;e.preventDefault();adjust(e.deltaY>0?-1:1)},{passive:false});let touchY=null;$('speed').addEventListener('pointerdown',e=>{touchY=e.clientY;$('speed').setPointerCapture(e.pointerId)});$('speed').addEventListener('pointerup',e=>{if(touchY!==null)adjust(touchY-e.clientY>8?1:touchY-e.clientY< -8?-1:1);touchY=null});
addEventListener('deviceorientation',e=>{if(!started||!Number.isFinite(e.gamma)||!Number.isFinite(e.beta))return;tiltSeen=true;motionStatus='ready';clearTimeout(orientationTimer);if(!tiltCenter){tiltCenter={gamma:e.gamma,beta:e.beta};say('TILT CENTERED · DOUBLE-TAP TO JUMP')}tiltInput=tiltControl(e.gamma,e.beta,tiltCenter)});
$('shell').addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;gestureStart={x:e.clientX,y:e.clientY,id:e.pointerId,target:e.target,time:performance.now()}});
$('shell').addEventListener('pointerup',e=>{if(!gestureStart||gestureStart.id!==e.pointerId)return;const startPoint=gestureStart;gestureStart=null;const end={x:e.clientX,y:e.clientY},action=gesture(startPoint,end,!$('help').hidden);if(action==='open'){openDrawer();return}if(action==='close'){closeDrawer();return}
  if(!started||paused||state.status!=='playing'||!isTap(startPoint,end)||startPoint.x>=240-GESTURE.edge||startPoint.target!==canvas){lastTap=null;return}
  const now=performance.now();if(lastTap&&now-lastTap.time<=GESTURE.doubleMs&&Math.hypot(lastTap.x-end.x,lastTap.y-end.y)<28){jumpQueued=true;lastTap=null;say('JUMP');beep(550)}else lastTap={...end,time:now};
});$('shell').addEventListener('pointercancel',()=>{gestureStart=null;lastTap=null});
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase())});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function frame(now){const dt=Math.min((now-last)/1000,1/30);last=now;if(started&&!paused&&state.status==='playing'&&motionStatus==='ready'){
  const brake=keys.has(' ')||keys.has('b')||brakePressed;
  state=step(state,{x:tiltInput.x*force/3,z:tiltInput.z*force/3,brake,jump:jumpQueued},dt,COURSE);jumpQueued=false;camera.x+=(state.x-camera.x)*Math.min(1,dt*3);camera.z+=(state.z+7-camera.z)*Math.min(1,dt*3);sync()
}draw();requestAnimationFrame(frame)}
const brakeButton=$('brake');brakeButton.addEventListener('pointerdown',e=>{e.preventDefault();brakeButton.setPointerCapture(e.pointerId);brakePressed=true});for(const ev of ['pointerup','pointercancel','lostpointercapture'])brakeButton.addEventListener(ev,()=>brakePressed=false);
$('audio').onclick=()=>{muted=!muted;const b=$('audio');b.setAttribute('aria-pressed',String(!muted));b.setAttribute('aria-label',muted?'Unmute audio':'Mute audio');b.title=muted?'Unmute audio':'Mute audio';if(!muted){audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume()}};
requestAnimationFrame(frame);
window.__lab=()=>({course:selected,difficulty,configuration:{sections:COURSE.sections,hazards:COURSE.hazards.length,features:COURSE.features.length,opponents:COURSE.opponents.length},state:{...state},tiltSeen,tiltCenter,tiltInput:{...tiltInput},motionStatus,force,started,paused,jumpQueued,muted});
// Local-only deterministic finish-zone browser fixture; never available on published Pages.
if(location.hostname==='127.0.0.1'||location.hostname==='localhost')window.__labSetState=patch=>{state={...state,...patch};sync()};
