import assert from 'node:assert/strict';import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true,executablePath:'/home/gtgb/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:240,height:282},hasTouch:true,isMobile:true});let errors=[];page.on('pageerror',e=>errors.push(e.message));
const read=()=>page.evaluate(()=>window.__lab());const cdp=await page.context().newCDPSession(page);
async function touch(x,y,dx=0,dy=0){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});if(dx||dy){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx,y:y+dy,id:1}]})}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})}
await page.goto('http://127.0.0.1:8765/',{waitUntil:'networkidle'});assert(await page.locator('#overlay').isVisible());
await page.evaluate(()=>{window.DeviceOrientationEvent=class extends Event{constructor(type,values){super(type);Object.assign(this,values)}}});
await page.locator('#difficulty').selectOption('pro');await page.locator('#course').selectOption('25');await page.locator('#start').tap();assert.equal((await read()).configuration.sections,26);assert.equal((await read()).state.lives,1);assert.equal((await read()).motionStatus,'waiting');let initial=await read();await page.waitForTimeout(120);assert.equal((await read()).state.remaining,initial.state.remaining,'wait for sensor does not consume clock');
await page.evaluate(()=>dispatchEvent(new DeviceOrientationEvent('deviceorientation',{gamma:14,beta:-9})));assert.equal((await read()).motionStatus,'ready');assert.deepEqual((await read()).tiltInput,{x:0,z:0});await page.waitForTimeout(150);assert.equal((await read()).state.falls,0);
await page.evaluate(()=>dispatchEvent(new DeviceOrientationEvent('deviceorientation',{gamma:30,beta:-9})));assert((await read()).tiltInput.x-(await read()).tiltInput.z>0);await page.waitForTimeout(280);assert(Math.hypot((await read()).state.vx,(await read()).state.vz)>.1);await page.evaluate(()=>dispatchEvent(new DeviceOrientationEvent('deviceorientation',{gamma:14,beta:-9})));
const box=await page.locator('#brake').boundingBox();const x=box.x+box.width/2,y=box.y+box.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await page.waitForTimeout(400);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(Math.hypot((await read()).state.vx,(await read()).state.vz)<.1);
assert.equal(await page.locator('#audio').getAttribute('aria-pressed'),'false');await page.locator('#audio').tap();assert.equal(await page.locator('#audio').getAttribute('aria-pressed'),'true');await page.locator('#audio').tap();assert.equal(await page.locator('#audio').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('#audio').getAttribute('aria-label'),'Unmute audio');
await touch(120,150);await page.waitForTimeout(90);await touch(120,150);await page.waitForTimeout(70);assert((await read()).state.jumpHeight>0,'double tap jump');await page.waitForTimeout(650);await touch(120,150);await page.waitForTimeout(380);assert.equal((await read()).state.jumpHeight,0,'single tap does not jump');
await touch(235,135,-65,2);assert(await page.locator('#help').isVisible());assert((await read()).paused);let paused=(await read()).state.remaining;await page.waitForTimeout(180);assert.equal((await read()).state.remaining,paused);await touch(120,140);assert((await read()).paused,'menu tap is not jump');await touch(45,140,70,0);assert(!(await page.locator('#help').isVisible()));assert(!(await read()).paused);await touch(150,120,-70,0);assert(!(await page.locator('#help').isVisible()),'middle swipe does not open drawer');
await page.locator('#speed').tap();assert.match(await page.locator('#speed').innerText(),/FORCE 4/);await page.evaluate(()=>window.__labSetState({x:0,z:155.45,vx:0,vz:2,remaining:48,fallTime:0,status:'playing'}));await page.waitForTimeout(80);assert.equal((await read()).state.status,'finished');assert(await page.locator('#result').isVisible());assert.match(await page.locator('#result-detail').innerText(),/Final Ascent/);assert(!(await page.locator('#next').isVisible()));await page.locator('#replay').tap();assert.equal((await read()).course,25);assert.equal((await read()).state.status,'playing');assert(!(await page.locator('#result').isVisible()));
await page.reload({waitUntil:'networkidle'});await page.locator('#start').tap();await page.waitForTimeout(2400);assert.equal((await read()).motionStatus,'unavailable');assert.match(await page.locator('#message').innerText(),/NO TILT DATA/);assert.equal((await read()).state.remaining,(await read()).state.remaining);
assert.deepEqual(errors,[]);const sizes=await page.evaluate(()=>({width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,buttons:[...document.querySelectorAll('button')].filter(b=>b.getBoundingClientRect().width&&b.getBoundingClientRect().height).map(b=>({id:b.id,rect:b.getBoundingClientRect().toJSON()}))}));assert.equal(sizes.width,240);assert.equal(sizes.height,282);assert(!sizes.buttons.some(b=>b.rect.right>240||b.rect.bottom>282));await page.screenshot({path:'browser-240x282.png'});console.log('240×282 touch: calibration, brake, jump, drawer, pause, audio, finish/replay, no-sensor passed');await browser.close();
