import assert from 'node:assert/strict';
import {COURSE,newGame,step,surfaceAt,surfaceHeight,surfaceSlope,TUNE} from './physics.js';
const tick=(s,input,n,course=COURSE)=>{for(let j=0;j<n;j++)s=step(s,input,1/60,course);return s};
const tile={id:0,x:0,z:0,w:100,l:100,h:0,dx:0,dz:0,kind:'stone'};
const flat={...COURSE,tiles:[tile],hazards:[],opponents:[],features:[],goal:{x:40,z:40},checkpoints:[{x:30,z:30}],spawn:{x:0,z:0}};
let s=tick(newGame(flat),{x:0,z:1},60,flat);assert(s.vz>3,'accelerates');const v=s.vz;s=tick(s,{x:0,z:0},8,flat);assert(s.vz>0&&s.vz<v,'coasts with resistance');assert(tick(s,{x:0,z:-1},10,flat).vz<s.vz,'countersteer brakes');
const uphill={...flat,tiles:[{...tile,dz:.25}]},downhill={...flat,tiles:[{...tile,dz:-.25}]};let ascend=tick(newGame(uphill),{z:1},30,uphill),descend=tick(newGame(downhill),{z:1},30,downhill);assert(descend.vz>ascend.vz+2,'slope acceleration');
const post={...flat,hazards:[{x:0,z:2,r:.58,kind:'post'}]};let impact=step({...newGame(post),x:0,z:.7,vz:10}, {},1/30,post);assert(impact.vz<0,'post collision reflects velocity');
const ledge={...flat,tiles:[{...tile,w:8,l:8}],checkpoints:[{x:0,z:0}],goal:{x:30,z:30}};let fall={...newGame(ledge),x:3.9,z:0,vx:9,checkpoint:1};for(let i=0;i<30&&fall.fallTime===0;i++)fall=step(fall,{},1/60,ledge);assert(fall.fallTime>0&&fall.falls===1,'open edge falls');for(let i=0;i<41;i++)fall=step(fall,{},1/60,ledge);assert.equal(fall.fallTime,0);assert(Math.hypot(fall.x,fall.z)<.1,'checkpoint respawn');assert(fall.remaining<ledge.seconds-4,'time penalty');
assert(!surfaceAt(70,70,flat));const finishCourse={...flat,tiles:[{...tile,kind:'goal'}],goal:{x:0,z:0}};let finish=step({...newGame(finishCourse),remaining:43.2},{},1/60,finishCourse);assert.equal(finish.status,'finished');assert.equal(step(finish,{},1/60,finishCourse).status,'finished');let jump=step(newGame(flat),{jump:true},1/60,flat);assert(jump.jumpHeight>0&&jump.y>TUNE.radius);for(let i=0;i<80;i++)jump=step(jump,{},1/60,flat);assert.equal(jump.jumpHeight,0);assert.equal(jump.status,'playing');console.log('physics: acceleration, coast, braking, slope, collision, open edge, checkpoint respawn, finish and jump passed');

for(const terrain of ['bank','bowl','ramp']){const t={...tile,w:10,l:10,terrain},c={...flat,tiles:[t]};let heights=[surfaceHeight(t,0,0),surfaceHeight(t,1,0),surfaceHeight(t,-1,0),surfaceHeight(t,0,1)];assert(heights.some(h=>Math.abs(h)>.1),`${terrain} has relief`);for(const v of [-5,0,5]){assert(Math.abs(surfaceHeight(t,-5,v))<1e-8&&Math.abs(surfaceHeight(t,5,v))<1e-8);assert(Math.abs(surfaceHeight(t,v,-5))<1e-8&&Math.abs(surfaceHeight(t,v,5))<1e-8)}let at={...newGame(c),x:1,z:0},next=step(at,{},1/60,c);assert(Math.abs(next.y-(surfaceHeight(t,next.x,next.z,next.elapsed)+TUNE.radius))<1e-6);if(terrain==='bowl'){assert(surfaceSlope(t,1,0).dx>0);assert(next.vx<0,'bowl rolls inward without input')}if(terrain==='bank'){assert(surfaceSlope(t,0,0).dx>0);assert(step(newGame(c),{},1/60,c).vx<0,'bank rolls downhill')}if(terrain==='ramp')assert(surfaceSlope(t,0,0).dz>0)}
console.log('bank, bowl and ramp: non-flat support, edge seams, slope-driven rolling and marble contact passed');
